language: node_js

node_js:
    - '0.12'

branches:
  only:
  - master
  - develop

services:
    - elasticsearch

before_script:
    - sleep 10

deploy:
  provider: npm
  email: dev@developmentseed.org
  api_key:
    secure: KU6UKUe+NUdIsRVn7sAnkGEPjXdSg4k/y2HMQ36AwqeZxbR7TM0AcgLBlavPGYKpzrF0fw/sOBdEl9Xk8phNHJnCyFhAx4/UFgrjo6yh+Tt2VAaD/uzmD4jJ4dg5aHjikxVWIJwUlaCrOx19UVLMgzLVf9Bexfr5/AAX2IrQE7mlGCX/LKgxwwVqPKFXJZYirFMnro0F5ih4dBAARHT6uAWMReQQNSsHaSlQLok0i0ijvMfST8uzWYcU4mFX1Lspz1oVh5goQNQQd+Gr1mrpyHKov7ZAx1+r2BCaxZ7LryKAIW1ZT5X4PpgH4U8NeDE+YPL/N0CHn7kzipT/Ny6VU5I7ZLQ9kVPcsRVnxwq7M1sZB1jsesKtEspYIQuRKaEAX7m5F9kB0XyogufphTydvj627vOdI+fimIGeGFO0YrwORISFSrSO6qGhIDcc4PtxaAadSqHs1wcwQ+RY6AF7rjerBU+ErhVxSVsTC04ZU8OILHNiIKvf3SCaW4+08Z3g4Lk78zCmoiXpLY1KNibzA4IPd5kdmHeFtS59cmiKvfOkePU0GwyOqfsIiwtmIyJciMDeLRy2l9g//U0rVeXrudb3kcWZ+yAXg662exzx8rtp7gtC3oDjZh75LMG+K3Ukyrxrl+q09EzVUkTXWb32n0UrhL3DUix+Eo+sift8wak=
  on:
    repo: developmentseed/landsat-meta-updater
    branch: master
